### ISSUE TITLE
OCR algorithm

### ISSUE THREAD

**Issue by mariam-khaled** [rehamessameltagoury/SugerCheck#2]
Goal: Extract ingredients from image.

- [x]  Preprocessing on image.
- [x]  Draw bounding boxes around characters.
- [x] Draw bounding boxes around words.
- [x] Get text representing ingredients from the image.
- [x]  Degree of safety

**Comment by mariam-khaled** [comment]
[] Draw bounding boxes around words.
[] Get text representing ingredients from the image.

**Comment by rehamessameltagoury** [comment]
- [ ] Degree of safety
